sonar.projectKey=Oumaymakhl_elearning-platform
sonar.organization=oumaymakhl

sonar.exclusions=\
  backend/**/config/jwt.php,\
  backend/**/config/app.php,\
  backend/**/vendor/**,\
  frontend/**/node_modules/**,\
  docker/**,\
  k8s/**

sonar.coverage.exclusions=\
  backend/**/config/**,\
  backend/**/database/**,\
  backend/**/vendor/**
