sonar.projectKey=Oumaymakhl_elearning-platform
sonar.organization=oumaymakhl

sonar.exclusions=\
  backend/**/config/jwt.php,\
  backend/**/config/app.php,\
  backend/**/vendor/**,\
  frontend/**/node_modules/**,\
  docker/**,\
  k8s/**,\
  backend/messaging-service/app/Http/Controllers/MessagingController.php,\
  backend/forum-service/app/Http/Controllers/ForumController.php

sonar.coverage.exclusions=\
  backend/**/config/**,\
  backend/**/database/**,\
  backend/**/vendor/**,\
  backend/**,\
  frontend/**

sonar.cpd.exclusions=\
  backend/**,\
  frontend/**
