server {
    listen 80;
    root /usr/share/nginx/html/browser;
    index index.html;

    location /api/ {
        proxy_pass http://172.18.0.36/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass_request_headers on;
    }

    location /storage {
        proxy_pass http://172.18.0.35/storage;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;
}
