server {
    listen 80;
    client_max_body_size 100M;
    root /usr/share/nginx/html/browser;
    index index.html;

    resolver 127.0.0.11 valid=10s;

    location /api/ {
        proxy_pass https://gateway/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass_request_headers on;
    }
    location /storage {
        proxy_pass http://nginx-user/storage;
        proxy_set_header Host $host;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;
}
