server {
    listen 80;
    server_name localhost;

    client_max_body_size 10M;

    location /api/auth/ {
        proxy_request_buffering off;
        rewrite ^/api/auth/(.*)$ /api/$1 break;
        proxy_pass http://nginx-auth;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-User-Data $http_x_user_data;
    }

    location /api/users {
        proxy_pass http://nginx-user;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-User-Data $http_x_user_data;
    }

    location /api/courses {
        proxy_pass http://nginx-course;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-User-Data $http_x_user_data;
    }

    location /api/contents {
        proxy_pass http://nginx-content;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-User-Data $http_x_user_data;
    }

    location /api/execute {
        proxy_pass http://nginx-executor;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-User-Data $http_x_user_data;
    }

    location /api/notifications {
        proxy_pass http://nginx-notification;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-User-Data $http_x_user_data;
    }

    location /api/quizzes {
        proxy_pass http://nginx-quiz;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-User-Data $http_x_user_data;
    }

    location /api/forum {
        proxy_pass http://nginx-forum;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-User-Data $http_x_user_data;
    }

    location /api/messaging {
        proxy_pass http://nginx-messaging;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-User-Data $http_x_user_data;
    }

    location = /api/generate-quiz {
        proxy_pass http://chatbot-service/api/generate-quiz;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-User-Data $http_x_user_data;
        proxy_read_timeout 90s;
        proxy_redirect off;
    }


    location /api/payments {
        proxy_pass http://nginx-payment;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-User-Data $http_x_user_data;
    }
    location /storage {
        proxy_pass http://nginx-user;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-User-Data $http_x_user_data;
    }
}
