server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    resolver 127.0.0.11 valid=10s ipv6=off;
    set $php_upstream messaging-service:9000;
    root /var/www/html/public;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass $php_upstream;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param Authorization $http_authorization;
        fastcgi_param HTTP_AUTHORIZATION $http_authorization;
        fastcgi_param REDIRECT_HTTP_AUTHORIZATION $http_authorization;
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_param REQUEST_METHOD $request_method;
        fastcgi_param QUERY_STRING $query_string;
        include fastcgi_params;
    }
}
